# Generated by Django 3.0.2 on 2020-01-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=250)),
                ('votes', models.IntegerField(null=True)),
                ('submitterAvatarUrl', models.ImageField(upload_to='images/avatar/')),
                ('productImageUrl', models.ImageField(upload_to='images/product/')),
            ],
        ),
    ]
