# Generated by Django 3.0.2 on 2020-01-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200111_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productImageUrl',
            field=models.ImageField(blank=True, default='default.png', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='submitterAvatarUrl',
            field=models.ImageField(blank=True, default='default.png', upload_to='images'),
        ),
    ]
