# Generated by Django 3.0.2 on 2020-01-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='url',
        ),
        migrations.AlterField(
            model_name='product',
            name='productImageUrl',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='submitterAvatarUrl',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
