# Generated by Django 3.0.2 on 2020-01-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200112_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productImageUrl',
            field=models.ImageField(blank=True, default='default.png', upload_to='product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='submitterAvatarUrl',
            field=models.ImageField(blank=True, default='default.png', upload_to='avatar'),
        ),
    ]
